"""reports table

Revision ID: 12d2f4020062
Revises: 41834f46154e
Create Date: 2014-06-23 10:26:11.927388

"""

# revision identifiers, used by Alembic.
revision = '12d2f4020062'
down_revision = '41834f46154e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
        sa.Column('submission_id', sa.Integer(), nullable=False),
        sa.Column('json_data', postgresql.JSON(), nullable=False),
        sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
        sa.PrimaryKeyConstraint('submission_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    ### end Alembic commands ###
