"""default_group_null

Revision ID: 2134c427f268
Revises: 12d2f4020062
Create Date: 2014-07-12 12:58:22.990613

"""

# revision identifiers, used by Alembic.
revision = '2134c427f268'
down_revision = '12d2f4020062'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'group',
               existing_type=sa.VARCHAR(),
               nullable=True,
               server_default=text('NULL'),
               existing_server_default="sm'::character varying")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'group',
               existing_type=sa.VARCHAR(),
               nullable=False,
               server_default='sm',
               existing_server_default="sm'::character varying")
    ### end Alembic commands ###
