"""unique index on skip type - municipality

Revision ID: 241611952129
Revises: 52c78849c2c6
Create Date: 2014-05-14 14:02:04.887513

"""

# revision identifiers, used by Alembic.
revision = '241611952129'
down_revision = '52c78849c2c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_skip_type_municipality_id', 'skips', ['skip_type', 'municipality_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skip_type_municipality_id', table_name='skips')
    ### end Alembic commands ###
