"""added status column

Revision ID: 2a19706e858
Revises: 45b373d8d8c7
Create Date: 2014-05-07 11:31:53.712224

"""

# revision identifiers, used by Alembic.
revision = '2a19706e858'
down_revision = '45b373d8d8c7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ENUM('pending', 'approved', 'rejected', name="SUBMISSION_STATUS").create(op.get_bind(), checkfirst=False)
    op.add_column('submissions', sa.Column('status', sa.Enum(name='SUBMISSION_STATUS'), nullable=False, server_default='pending'))
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_column('submissions', 'status')
    ENUM(name="SUBMISSION_STATUS").drop(op.get_bind(), checkfirst=False)
    ### end Alembic commands ###