"""drop daily_waste and submission_type

Revision ID: 3a28bde53cbe
Revises: 4a171f7a4676
Create Date: 2014-05-22 17:04:19.384001

"""

# revision identifiers, used by Alembic.
revision = '3a28bde53cbe'
down_revision = '4a171f7a4676'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_wastes')
    op.drop_column('submissions', 'submission_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('submission_type', sa.VARCHAR(length=50), server_default="submission", autoincrement=False, nullable=False))
    op.create_index('ix_submissions_submission_type', 'submissions', ['submission_type'], unique=False)
    op.create_table('daily_wastes',
    sa.Column('id', sa.INTEGER(), server_default="nextval('daily_wastes_id_seq'::regclass)", nullable=False),
    sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], [u'submissions.id'], name=u'daily_wastes_submission_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'daily_wastes_pkey')
    )
    ### end Alembic commands ###
