"""Site Reports

Revision ID: 3bd65e9ea117
Revises: 2134c427f268
Create Date: 2014-08-06 13:55:34.158509

"""

# revision identifiers, used by Alembic.
revision = '3bd65e9ea117'
down_revision = '2134c427f268'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'site_reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date_created',
                  sa.Date(),
                  server_default='1970-01-01',
                  nullable=False),
        sa.Column('report_json', postgresql.JSON(), nullable=False),
        sa.Column('municipality_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_reports')
    ### end Alembic commands ###
