"""add municipalities table

Revision ID: 45b373d8d8c7
Revises: 4ec2894c2731
Create Date: 2014-05-06 14:16:43.362455

"""

# revision identifiers, used by Alembic.
revision = '45b373d8d8c7'
down_revision = '4ec2894c2731'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('municipalities')
    ### end Alembic commands ###
