"""create users table

Revision ID: 47e593b61a6d
Revises: 284ec1ec97ae
Create Date: 2014-06-16 13:14:49.839355

"""

# revision identifiers, used by Alembic.
revision = '47e593b61a6d'
down_revision = '284ec1ec97ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('pwd', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False, server_default='false'),
    sa.UniqueConstraint('username'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
