"""add date to submissions

Revision ID: 4a171f7a4676
Revises: 69903951dae
Create Date: 2014-05-22 16:16:59.521364

"""

# revision identifiers, used by Alembic.
revision = '4a171f7a4676'
down_revision = '69903951dae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('municipality_submissions', 'date')
    op.add_column('submissions', sa.Column('date', sa.Date(), server_default='1970-01-01', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'date')
    op.add_column('municipality_submissions', sa.Column('date', sa.DATE(), server_default='1970-01-01', nullable=False))
    ### end Alembic commands ###
