"""added skip model

Revision ID: 52c78849c2c6
Revises: 2a19706e858
Create Date: 2014-05-12 13:19:18.958998

"""

# revision identifiers, used by Alembic.
revision = '52c78849c2c6'
down_revision = '2a19706e858'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skip_type', sa.String(length=2), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('small_length', sa.Float(), nullable=False),
    sa.Column('large_length', sa.Float(), nullable=False),
    sa.Column('small_breadth', sa.Float(), nullable=False),
    sa.Column('large_breadth', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skips')
    ### end Alembic commands ###
